version: "3.7"
services:
    apka:
        build: ./
        ports:
        - "5000:5000"
        volumes:
        - "./:/code"
        # docker run -p 3000^C000 -v $(pwd):/code sroda
    database:
        image: mongo
        volumes:
        - "mongo_volume:/data/db"

volumes:
    mongo_volume:
