#!/bin/bash -eu

echo "Found file: magic.conf"
echo "Found file: sshd.conf"
echo "Found file: plik.conf"
echo >&2 "Permission denied to B directory"
echo "Found file: ssh_conf"
echo "Found file: magic.conf"
echo "Found file: magic.conf"
echo >&2 "PERMISSION DENIED do A file"
echo >&2 "PERMISSION DENIED do A file"
echo "Found file: magic.conf"
echo "Found file: magic.conf"
echo >&2 "Some random error"
echo >&2 "Not a permission denied error"
echo >&2 "PERMISSION DENIED do A file"
echo "Found file: sshd.conf"
echo >&2 "Random error"
echo "Found file: magic.conf"